# Generated by Django 3.2.12 on 2022-08-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20220802_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, verbose_name='Теги')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Список постов', 'verbose_name_plural': 'Список постов'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blog_app.Tags'),
        ),
    ]
